### PR TITLE
Delete refactoring_request.md

### PR DESCRIPTION
**Pull request by nicolasmondada**
Removing refactoring request template to streamline issue submission process.

### CODE REVIEW

**Review by NSeydoux — COMMENTED** [review]
Let's say you are an external contributor, you look at the code, and you see a pattern that you would like to implement in order to enable a new feature. Submitting a refactoring ticket makes it possible to have a discussion about the architecture before implementing anything, and without going into details in the fetaure it allows. How would one do this without this type of ticket ?

**Review by Vinnl — APPROVED** [review]
@NSeydoux If it's to implement a new feature, I'd just use the Feature Request template. If it's really just a refactoring, then I haven't seen that happening too often, but if that does happen, it's always an option [not to use an issue template](https://github.com/inrupt/solid-client-js/issues/new).

**Review by Vinnl — COMMENTED** [review]
Ah oops, didn't see Nicolas S. didn't approve - removing my approval until his question was satisfactorily addressed :)

**Comment by NSeydoux** [comment]
Oh no don't worry, I'm fine with your explanation so I'm happy to remove this template :)

**Review by Vinnl — APPROVED** [review]

**Pull request merged**
